import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';
import Sidebar from '@/components/Sidebar';

const font = Lexend_Deca({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Anix -  Watch Anime Online - Free Anime Streaming',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={font.className}>
                <Header></Header>
                <Sidebar>{children}</Sidebar>
            </body>
        </html>
    );
}
